# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duyuru', models.TextField(default='', max_length=250, verbose_name='Duyuru')),
                ('tur', models.CharField(choices=[('primary', 'Onemli'), ('warning', 'Bilgilendirme'), ('danger', 'Acil')], default='', max_length=150, verbose_name='Tür')),
                ('is_homepage', models.BooleanField(default=False, verbose_name='Paylaşılsın mı?')),
            ],
        ),
    ]
