# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adimlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim', models.PositiveIntegerField(default=1, verbose_name='Adım Sırası')),
                ('soru', models.TextField(default='', verbose_name='Soru')),
                ('kisa_aciklama', models.TextField(default='', verbose_name='Açıklama')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Robotlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot', models.CharField(max_length=300, verbose_name='Robot')),
                ('kategori', models.CharField(choices=[('Çizgi Futbol', 'Çizgi Futbol'), ('Merdiven Çıkan', 'Merdiven Çıkan'), ('ROBO Senaryo:Lojistik', 'ROBO Senaryo : Lojistik'), ('İnşaat', 'İnşaat'), ('FANUC Drone', 'FANUC Drone'), ('Renk Seçen', 'Renk Seçen'), ('Mikro Sumo', 'Mikro Sumo'), ('Trafik', 'Trafik')], default='', max_length=300, verbose_name='Kategori')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşma Tarihi')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Siralar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(default=1, help_text='Futbol(a-b)\tMerdiven(c-d)\tSenaryo(f-e)\tİnşaat(a-b)\tDrone(c-d)\tRenk(f-e)\tMikro(a-b)\tTrafik(c-d)', verbose_name='Robot Sırası')),
                ('current_ctgr', models.CharField(choices=[('Çizgi Futbol', 'Çizgi Futbol'), ('Merdiven Çıkan', 'Merdiven Çıkan'), ('ROBO Senaryo:Lojistik', 'ROBO Senaryo : Lojistik'), ('İnşaat', 'İnşaat'), ('FANUC Drone', 'FANUC Drone'), ('Renk Seçen', 'Renk Seçen'), ('Mikro Sumo', 'Mikro Sumo'), ('Trafik', 'Trafik')], default='', max_length=250, verbose_name='Şu an oynanan kategori')),
                ('is_live', models.BooleanField(default=False, verbose_name='Şu an oynanıyor mu?')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
