# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-01 13:44
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konusmacilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konusmaci', models.CharField(max_length=300, verbose_name='Isim/Soyisim')),
                ('who', ckeditor.fields.RichTextField(verbose_name='hakkinda')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşma Tarihi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Kapak Fotoğrafı')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
