# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-03-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=250, verbose_name='Etkinlik Adı')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşma Tarihi')),
                ('isimSoyisim', models.CharField(default='', max_length=150, verbose_name='isim - soyisim')),
                ('opinion', models.TextField(blank=True, max_length=750, null=True, verbose_name='Görüş')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-Posta')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşma Tarihi')),
                ('isimSoyisim', models.CharField(default='', max_length=150, verbose_name='isim - soyisim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='ani')),
                ('slug', models.SlugField(default='', editable=False, max_length=130, unique=True)),
                ('email', models.EmailField(default='', max_length=254, verbose_name='E-Posta')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleFriday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Başlık')),
                ('speaker', models.CharField(blank=True, max_length=150, null=True, verbose_name='Konuşmacı/KAT(?)')),
                ('hour_slice', models.CharField(max_length=100, verbose_name='Saat Dilimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_competetion', models.BooleanField(default=False, verbose_name='Yarışma mı?')),
                ('related_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ituro_event.Event')),
            ],
            options={
                'verbose_name_plural': 'Cumalar',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSaturday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Başlık')),
                ('speaker', models.CharField(blank=True, max_length=150, null=True, verbose_name='Konuşmacı/KAT(?)')),
                ('hour_slice', models.CharField(max_length=100, verbose_name='Saat Dilimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_competetion', models.BooleanField(default=False, verbose_name='Yarışma mı?')),
                ('related_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ituro_event.Event')),
            ],
            options={
                'verbose_name_plural': 'Cumartesiler',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleThursday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Başlık')),
                ('speaker', models.CharField(blank=True, max_length=150, null=True, verbose_name='Konuşmacı/KAT(?)')),
                ('hour_slice', models.CharField(max_length=100, verbose_name='Saat Dilimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_competetion', models.BooleanField(default=False, verbose_name='Yarışma mı?')),
                ('related_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ituro_event.Event')),
            ],
            options={
                'verbose_name_plural': 'Perşembeler',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
